app:
    resource: "@AppBundle/Controller/"
    prefix: /
    type:   annotation
api:
    resource: "@AppBundle/Controller/API"
    prefix: /api
    type:   annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
